export type DemoTaskStatus = "todo" | "in_progress" | "done";
export type DemoSupplierStatus = "pending" | "confirmed" | "paid";
export type DemoPaymentStatus = "unpaid" | "partial" | "paid";

export const demoEventManagementData = {
  event: {
    _id: "demo-event-001",
    title: "החתונה של עדי ודניאל",
    eventType: "חתונה",
    date: "2026-09-15",
    time: "19:30",
    location: "אולם בראשית, נס ציונה",
    hallName: "בראשית",
    hallRoom: "אולם גפן",
    estimatedGuests: 320,
    confirmedGuests: 248,
    pendingGuests: 52,
    declinedGuests: 20,
    actualArrived: 0,
    contactName: "עדי לוי",
    contactPhone: "050-1234567",
    notes: "אירוע דמו להתנסות במערכת. הנתונים לא נשמרים.",
  },

  overviewStats: {
    totalGuests: 320,
    confirmedGuests: 248,
    pendingGuests: 52,
    declinedGuests: 20,
    tables: 32,
    suppliers: 8,
    openTasks: 6,
    completedTasks: 9,
    totalBudget: 120000,
    paidAmount: 74000,
    remainingAmount: 46000,
  },

  tasks: [
    {
      _id: "task-001",
      title: "אישור סופי מול האולם",
      description: "לוודא שעה, סידור שולחנות, כמות מנות ומנהל אירוע.",
      status: "in_progress" as DemoTaskStatus,
      dueDate: "2026-09-01",
      priority: "high",
      owner: "עדי",
    },
    {
      _id: "task-002",
      title: "סגירת רשימת ספקים",
      description: "לוודא שכל הספקים אישרו הגעה וקיבלו כתובת.",
      status: "todo" as DemoTaskStatus,
      dueDate: "2026-08-25",
      priority: "medium",
      owner: "דניאל",
    },
    {
      _id: "task-003",
      title: "אישור עיצוב הזמנה",
      description: "לעבור על נוסח ההזמנה והעיצוב הסופי.",
      status: "done" as DemoTaskStatus,
      dueDate: "2026-08-10",
      priority: "low",
      owner: "עדי",
    },
  ],

  suppliers: [
    {
      _id: "supplier-001",
      category: "צילום",
      businessName: "Studio Moments",
      contactName: "רועי",
      phone: "050-2222222",
      status: "confirmed" as DemoSupplierStatus,
      price: 8500,
      paid: 3000,
      notes: "כולל וידאו, סטילס ואלבומים.",
    },
    {
      _id: "supplier-002",
      category: "DJ",
      businessName: "DJ Event Pro",
      contactName: "מאור",
      phone: "052-3333333",
      status: "pending" as DemoSupplierStatus,
      price: 6500,
      paid: 1000,
      notes: "צריך לשלוח רשימת שירים.",
    },
    {
      _id: "supplier-003",
      category: "איפור ושיער",
      businessName: "Beauty Bride",
      contactName: "לינוי",
      phone: "054-4444444",
      status: "paid" as DemoSupplierStatus,
      price: 4200,
      paid: 4200,
      notes: "כולל ליווי לאולם.",
    },
  ],

  budgetItems: [
    {
      _id: "budget-001",
      title: "אולם",
      category: "מקום האירוע",
      total: 82000,
      paid: 50000,
      status: "partial" as DemoPaymentStatus,
      dueDate: "2026-09-01",
    },
    {
      _id: "budget-002",
      title: "צילום",
      category: "ספקים",
      total: 8500,
      paid: 3000,
      status: "partial" as DemoPaymentStatus,
      dueDate: "2026-08-20",
    },
    {
      _id: "budget-003",
      title: "DJ",
      category: "ספקים",
      total: 6500,
      paid: 1000,
      status: "partial" as DemoPaymentStatus,
      dueDate: "2026-08-25",
    },
    {
      _id: "budget-004",
      title: "עיצוב אולם",
      category: "עיצוב",
      total: 12000,
      paid: 0,
      status: "unpaid" as DemoPaymentStatus,
      dueDate: "2026-09-05",
    },
  ],

  schedule: [
    {
      _id: "schedule-001",
      time: "18:30",
      title: "הגעת ספקים",
      description: "צילום, DJ, עיצוב ואולם.",
      responsible: "מנהל אירוע",
    },
    {
      _id: "schedule-002",
      time: "19:30",
      title: "קבלת פנים",
      description: "פתיחת עמדות אוכל ובר.",
      responsible: "אולם",
    },
    {
      _id: "schedule-003",
      time: "20:30",
      title: "חופה",
      description: "לוודא הורים, עדים וטבעות מוכנים.",
      responsible: "מנהל אירוע",
    },
    {
      _id: "schedule-004",
      time: "21:15",
      title: "פתיחת רחבה",
      description: "שיר כניסה + תחילת ריקודים.",
      responsible: "DJ",
    },
  ],

  notes: [
    {
      _id: "note-001",
      title: "משפחה קרובה",
      text: "לוודא ששולחנות המשפחה קרובים לחופה.",
      createdAt: "2026-08-01",
    },
    {
      _id: "note-002",
      title: "אורחים רגישים",
      text: "יש אורחים שצריכים מנה צמחונית וללא גלוטן.",
      createdAt: "2026-08-03",
    },
  ],

  files: [
    {
      _id: "file-001",
      name: "חוזה אולם.pdf",
      type: "PDF",
      size: "1.2MB",
      uploadedAt: "2026-08-01",
    },
    {
      _id: "file-002",
      name: "רשימת שירים.docx",
      type: "DOCX",
      size: "320KB",
      uploadedAt: "2026-08-05",
    },
  ],
};