export type DemoTourAdvance = "continue" | "action" | "click" | "input";

export type DemoTourStep = {
  id: string;
  topic: string;
  title: string;
  learn: string;
  body: string;
  route: string;
  /** Highlight the control on the current screen instead of jumping routes. */
  stay?: boolean;
  selector: string;
  advance: DemoTourAdvance;
  action?: string;
};

export const DEMO_TOUR_TOPICS = [
  { id: "start", label: "דשבורד" },
  { id: "invite", label: "הזמנה" },
  { id: "event", label: "פרטי האירוע" },
  { id: "gifts", label: "מתנות" },
  { id: "guests", label: "מוזמן עם טלפון" },
  { id: "family", label: "בלי טלפון" },
  { id: "messages", label: "הודעות" },
  { id: "recorded", label: "שיחות מוקלטות" },
  { id: "human", label: "שיחות אנושיות" },
  { id: "seating", label: "הושבה" },
  { id: "checkin", label: "כניסה לאירוע" },
  { id: "summary", label: "סיכום" },
] as const;

const DASH = "/try/dashboard";
const EVENT = "/try/dashboard/invitations/demo-invitation/edit";
const INVITE = "/try/dashboard/edit-invite/demo-invitation";
const MESSAGES = "/try/dashboard/messages/new";
const CALLS = "/try/dashboard/recorded-calls";
const SEATING = "/try/dashboard/seating";
const CHECKIN = "/try/dashboard/check-in";

export const DEMO_TOUR_STEPS: DemoTourStep[] = [
  {
    id: "dashboard",
    topic: "start",
    title: "תמונת המצב של האירוע",
    learn: "איפה רואים מגיעים וממתינים",
    body: "הכרטיסים האלה מתעדכנים לפי הפעולות בדמו: מי מגיע, מי עדיין לא ענה, ומה קרה לאחרונה.",
    route: DASH,
    selector: "#rsvp-stats",
    advance: "continue",
  },
  {
    id: "menu",
    topic: "start",
    title: "התפריט הראשי",
    learn: "איך עוברים בין המסכים",
    body: "מכאן מתחילים בהזמנה, ואחר כך פרטי האירוע, מוזמנים, הודעות, שיחות, הושבה וכניסה. במובייל פותחים קודם את התפריט.",
    route: DASH,
    stay: true,
    selector: "[data-tour='customer-nav']",
    advance: "continue",
  },
  {
    id: "go-invite",
    topic: "invite",
    title: "כניסה למסך ההזמנה",
    learn: "איך מגיעים לתמונת ההזמנה",
    body: "לחצו על ״הזמנה״. במסך הזה מחליפים את תמונת ההזמנה ורואים תצוגה מקדימה.",
    route: DASH,
    stay: true,
    selector: "[data-tour='nav-invitation']",
    advance: "click",
  },
  {
    id: "invite-upload",
    topic: "invite",
    title: "החלפת תמונת ההזמנה",
    learn: "איך מעלים הזמנה",
    body: "לחצו החלפת תמונה, בחרו קובץ, ואז שמרו. התמונה נשמרת רק בדמו.",
    route: INVITE,
    selector: "[data-tour='invite-upload']",
    advance: "action",
    action: "invite-image",
  },
  {
    id: "invite-preview",
    topic: "invite",
    title: "תצוגה מקדימה לאורח",
    learn: "איך האורח רואה את ההזמנה",
    body: "לחצו תצוגה מקדימה. נפתח הקישור כפי שהאורח רואה אותו, בלי שליחה אמיתית.",
    route: INVITE,
    selector: "[data-tour='invite-preview']",
    advance: "click",
  },
  {
    id: "go-event",
    topic: "event",
    title: "כניסה להגדרת פרטי האירוע",
    learn: "איך מגיעים למסך הפרטים",
    body: "אחרי ההזמנה חוזרים לתפריט. לחצו על ״הגדרת פרטי אירוע״.",
    route: INVITE,
    stay: true,
    selector: "[data-tour='nav-event-details']",
    advance: "click",
  },
  {
    id: "event-title",
    topic: "event",
    title: "שם האירוע",
    learn: "איך משנים את השם",
    body: "שנו מעט את שם האירוע. השינוי נשמר רק בדמו, אחרי לחיצה על שמירה.",
    route: EVENT,
    selector: "[data-tour='event-title']",
    advance: "input",
  },
  {
    id: "event-hosts",
    topic: "event",
    title: "שמות בעלי השמחה",
    learn: "איפה רושמים את השמות",
    body: "כאן מופיעים השמות שיראו האורחים. אפשר לעדכן אותם עכשיו.",
    route: EVENT,
    selector: "[data-tour='event-hosts']",
    advance: "input",
  },
  {
    id: "event-date",
    topic: "event",
    title: "תאריך האירוע",
    learn: "איפה קובעים תאריך",
    body: "בחרו תאריך. הוא יוצג בדשבורד, בהזמנה ובקישור של האורח.",
    route: EVENT,
    selector: "[data-tour='event-date']",
    advance: "input",
  },
  {
    id: "event-time",
    topic: "event",
    title: "שעת האירוע",
    learn: "איפה קובעים שעה",
    body: "עדכנו את השעה. גם היא חלק מפרטי האירוע שמוצגים לאורחים.",
    route: EVENT,
    selector: "[data-tour='event-time']",
    advance: "input",
  },
  {
    id: "event-place",
    topic: "event",
    title: "מיקום האירוע",
    learn: "איפה רושמים אולם",
    body: "הקלידו או בחרו את שם האולם. הניווט של האורחים נפתח מהנקודה הזו.",
    route: EVENT,
    selector: "[data-tour='event-location']",
    advance: "input",
  },
  {
    id: "event-save",
    topic: "event",
    title: "שמירת פרטי האירוע",
    learn: "איך השינוי נכנס לנתונים",
    body: "לחצו שמירה. הפרטים מתעדכנים בדמו בלבד, בלי לגעת באירוע אמיתי.",
    route: EVENT,
    selector: "[data-tour='event-save']",
    advance: "action",
    action: "event-details",
  },
  {
    id: "go-dashboard-details",
    topic: "event",
    title: "חזרה לדשבורד",
    learn: "איך רואים את מה שנשמר",
    body: "לחצו על ״דשבורד״ בתפריט כדי לראות את הפרטים המעודכנים.",
    route: EVENT,
    stay: true,
    selector: "[data-tour='nav-dashboard']",
    advance: "click",
  },
  {
    id: "event-saved",
    topic: "event",
    title: "הפרטים שעודכנו",
    learn: "איפה רואים שם, תאריך ושעה",
    body: "הכרטיס הזה מציג את השם, התאריך, השעה והמיקום כפי שנשמרו בדמו.",
    route: DASH,
    selector: "[data-tour='event-summary']",
    advance: "continue",
  },
  {
    id: "event-on-invite",
    topic: "event",
    title: "הפרטים בהזמנה",
    learn: "איפה האורח רואה את מה שנשמר",
    body: "לחצו על ״הזמנה״. שם נמצאת התצוגה שהאורח רואה, עם השם והמיקום שנשמרו.",
    route: DASH,
    stay: true,
    selector: "[data-tour='nav-invitation']",
    advance: "click",
  },
  {
    id: "event-invite-view",
    topic: "event",
    title: "תצוגת האורח אחרי השמירה",
    learn: "איך הפרטים נראים בהזמנה",
    body: "זו תצוגת הטלפון. השם והמיקום שעודכנו מופיעים בעמוד שהאורח פותח.",
    route: INVITE,
    selector: "[data-tour='invite-guest-view']",
    advance: "continue",
  },
  {
    id: "go-gifts",
    topic: "gifts",
    title: "חזרה לפרטי האירוע",
    learn: "איפה מגדירים מתנות",
    body: "קישורי המתנה נמצאים בהגדרת פרטי האירוע, לא בסבב ההודעות. לחצו על הפריט בתפריט.",
    route: INVITE,
    stay: true,
    selector: "[data-tour='nav-event-details']",
    advance: "click",
  },
  {
    id: "gift-credit",
    topic: "gifts",
    title: "מתנה באשראי",
    learn: "איך מפעילים קישור אשראי",
    body: "סמנו מתנה באשראי. אחר כך מדביקים קישור שמתחיל ב-https.",
    route: EVENT,
    selector: "[data-tour='gift-credit']",
    advance: "click",
  },
  {
    id: "gift-credit-url",
    topic: "gifts",
    title: "קישור האשראי",
    learn: "איך ממלאים את הקישור",
    body: "הדביקו קישור לדוגמה, למשל https://demo.invistimo.com/gift. זה לא תשלום אמיתי.",
    route: EVENT,
    selector: "[data-tour='gift-credit-url']",
    advance: "input",
  },
  {
    id: "gift-paybox",
    topic: "gifts",
    title: "PayBox",
    learn: "איך מוסיפים PayBox",
    body: "סמנו PayBox. הקישור יופיע אחר כך בקישור האישי של האורח.",
    route: EVENT,
    selector: "[data-tour='gift-paybox']",
    advance: "click",
  },
  {
    id: "gift-paybox-url",
    topic: "gifts",
    title: "קישור PayBox",
    learn: "איך שומרים קישור PayBox",
    body: "הדביקו קישור שמתחיל ב-https. בדמו לא נפתח תשלום.",
    route: EVENT,
    selector: "[data-tour='gift-paybox-url']",
    advance: "input",
  },
  {
    id: "gift-bit",
    topic: "gifts",
    title: "Bit",
    learn: "איך מוסיפים Bit",
    body: "סמנו Bit. האורח יראה את מספר הטלפון לקבלת המתנה.",
    route: EVENT,
    selector: "[data-tour='gift-bit']",
    advance: "click",
  },
  {
    id: "gift-bit-phone",
    topic: "gifts",
    title: "מספר Bit",
    learn: "איך רושמים את המספר",
    body: "הקלידו מספר לדוגמה. הוא נשמר רק בנתוני הדמו.",
    route: EVENT,
    selector: "[data-tour='gift-bit-phone']",
    advance: "input",
  },
  {
    id: "gift-save",
    topic: "gifts",
    title: "שמירת קישורי המתנה",
    learn: "איך הקישורים נכנסים להזמנה",
    body: "לחצו שמירה. אשראי, PayBox ו-Bit יישמרו בדמו ויופיעו בקישור של האורח.",
    route: EVENT,
    selector: "[data-tour='event-save']",
    advance: "action",
    action: "event-details",
  },
  {
    id: "gift-on-link",
    topic: "gifts",
    title: "המתנות בקישור האישי",
    learn: "איפה האורח רואה את הקישורים",
    body: "לחצו על ״הזמנה״. התצוגה הזו היא הקישור האישי שהאורח פותח.",
    route: EVENT,
    stay: true,
    selector: "[data-tour='nav-invitation']",
    advance: "click",
  },
  {
    id: "gift-link-view",
    topic: "gifts",
    title: "כך המתנות מופיעות לאורח",
    learn: "אשראי, PayBox ו-Bit בעמוד",
    body: "בתצוגת הטלפון מופיעים קישור האשראי, PayBox ומספר ה-Bit שנשמרו.",
    route: INVITE,
    selector: "[data-tour='invite-guest-view']",
    advance: "continue",
  },
  {
    id: "go-guests",
    topic: "guests",
    title: "רשימת המוזמנים",
    learn: "איך נכנסים לרשימה",
    body: "לחצו על ״רשימת מוזמנים״. שם מוסיפים אורחים ורואים את יתרת הרשומות.",
    route: EVENT,
    stay: true,
    selector: "[data-tour='nav-guests']",
    advance: "click",
  },
  {
    id: "records-before",
    topic: "guests",
    title: "יתרת הרשומות לפני",
    learn: "מה נספר בחבילה",
    body: "רק מוזמן עם מספר טלפון מוריד רשומה בתשלום. זכרו את המספר שנשאר.",
    route: DASH,
    selector: "[data-tour='records-balance']",
    advance: "continue",
  },
  {
    id: "add-guest",
    topic: "guests",
    title: "מוזמן עם טלפון",
    learn: "איך מוסיפים רשומה לחיוב",
    body: "לחצו הוספת מוזמן, מלאו שם ומספר טלפון, ושמרו. היתרה תרד באחת.",
    route: DASH,
    selector: "[data-tour='add-guest']",
    advance: "action",
    action: "add-guest",
  },
  {
    id: "guest-edit",
    topic: "guests",
    title: "כרטיס המוזמן",
    learn: "איך פותחים עריכה",
    body: "לחצו על עיפרון העריכה בשורת המוזמן. הכרטיס נפתח מעל ההדרכה.",
    route: DASH,
    selector: "[data-tour='guest-edit']",
    advance: "click",
  },
  {
    id: "guest-name",
    topic: "guests",
    title: "עריכת שם",
    learn: "איך מעדכנים פרט",
    body: "שנו את השם בכרטיס. בשלב הבא שומרים את השינוי.",
    route: DASH,
    selector: "[data-tour='guest-edit-name']",
    advance: "input",
  },
  {
    id: "guest-save",
    topic: "guests",
    title: "שמירת המוזמן",
    learn: "איך העדכון נכנס לרשימה",
    body: "לחצו שמור שינויים. הרשימה והדשבורד מתעדכנים בדמו.",
    route: DASH,
    selector: "[data-tour='guest-edit-save']",
    advance: "action",
    action: "update-guest",
  },
  {
    id: "records-after",
    topic: "guests",
    title: "היתרה אחרי הוספה",
    learn: "איך רואים שהרשומה ירדה",
    body: "המספר כאן קטן באחת לעומת מה שראיתם לפני המוזמן עם הטלפון.",
    route: DASH,
    selector: "[data-tour='records-balance']",
    advance: "continue",
  },
  {
    id: "add-family",
    topic: "family",
    title: "קרוב משפחה בלי טלפון",
    learn: "רשומה שלא מיועדת לאישורי הגעה",
    body: "הוסיפו מוזמן עם שם, והשאירו את הטלפון ריק. הוא מיועד להושבה ולכניסה, לא לשליחת הודעה.",
    route: DASH,
    selector: "[data-tour='add-guest']",
    advance: "action",
    action: "add-guest-free",
  },
  {
    id: "records-same",
    topic: "family",
    title: "היתרה לא ירדה",
    learn: "למה רשומה בלי טלפון לא מחויבת",
    body: "המספר נשאר זהה. לפי כללי החיוב, רשומה בלי טלפון לא מפחיתה את יתרת הרשומות בתשלום.",
    route: DASH,
    selector: "[data-tour='records-balance']",
    advance: "continue",
  },
  {
    id: "guest-link",
    topic: "family",
    title: "הקישור האישי",
    learn: "איך האורח רואה מתנות והזמנה",
    body: "לחצו על סימן הקישור. זה הדף האישי של האורח, כולל ההזמנה וקישורי המתנה.",
    route: DASH,
    selector: "[data-tour='guest-link']",
    advance: "click",
  },
  {
    id: "go-messages",
    topic: "messages",
    title: "כניסה לשליחת הודעות",
    learn: "איך מתחילים סבב",
    body: "לחצו על ״שליחת הודעות״. ניצור סבב אישורי הגעה בלי לשלוח הודעה אמיתית.",
    route: DASH,
    stay: true,
    selector: "[data-tour='nav-messages']",
    advance: "click",
  },
  {
    id: "channel-wa",
    topic: "messages",
    title: "ערוץ WhatsApp",
    learn: "בחירה באישורי הגעה",
    body: "בסבב אישורי הגעה אפשר לבחור WhatsApp. לחצו עליו כדי לראות את האפשרות.",
    route: MESSAGES,
    selector: "[data-tour='message-channel-whatsapp']",
    advance: "click",
  },
  {
    id: "channel-sms",
    topic: "messages",
    title: "ערוץ SMS",
    learn: "האפשרות השנייה לאישורי הגעה",
    body: "אפשר גם SMS. בחרו SMS כדי שההדגמה תישאר בערוץ שזמין בלי תבנית חיצונית.",
    route: MESSAGES,
    selector: "[data-tour='message-channel-sms']",
    advance: "click",
  },
  {
    id: "audience",
    topic: "messages",
    title: "קהל היעד",
    learn: "למי הסבב נשלח",
    body: "סבב 1 יוצא למי שיש לו טלפון. סבבים 2 ו-3 יוצאים למי שטרם אישר. כאן רואים את כמות הנמענים.",
    route: MESSAGES,
    selector: "[data-tour='message-audience']",
    advance: "continue",
  },
  {
    id: "timing-now",
    topic: "messages",
    title: "שליחה מיידית",
    learn: "שליחה עכשיו",
    body: "לחצו שליחה מיידית. כך רואים את האפשרות לשלוח ברגע השמירה.",
    route: MESSAGES,
    selector: "[data-tour='message-timing-now']",
    advance: "click",
  },
  {
    id: "timing-later",
    topic: "messages",
    title: "תזמון שליחה",
    learn: "שליחה במועד עתידי",
    body: "לחצו שליחה מתוזמנת. ההודעה תסומן למועד שתבחרו, בלי לצאת באמת.",
    route: MESSAGES,
    selector: "[data-tour='message-timing-scheduled']",
    advance: "click",
  },
  {
    id: "schedule-when",
    topic: "messages",
    title: "תאריך ושעה",
    learn: "איך קובעים מועד",
    body: "בחרו תאריך ושעה. במועד הזה הסבב היה אמור לצאת. בדמו הוא רק נרשם.",
    route: MESSAGES,
    selector: "[data-tour='message-schedule']",
    advance: "input",
  },
  {
    id: "message-send",
    topic: "messages",
    title: "שמירת הסבב",
    learn: "איך מסיימים בלי שליחה אמיתית",
    body: "לחצו על כפתור השליחה. תופיע הצלחה, והסבב יישמר כמתוזמן בדמו בלבד.",
    route: MESSAGES,
    selector: "[data-tour='message-send']",
    advance: "action",
    action: "simulate-send",
  },
  {
    id: "reminder-tab",
    topic: "messages",
    title: "הודעה שאינה אישור הגעה",
    learn: "איפה רואים ערוץ אחר",
    body: "לחצו על תזכורת. זה סוג הודעה נפרד מסבב אישורי ההגעה.",
    route: MESSAGES,
    selector: "[data-tour='message-tab-reminder']",
    advance: "click",
  },
  {
    id: "reminder-sms",
    topic: "messages",
    title: "תזכורת ב-SMS בלבד",
    learn: "לפי הכללים הקיימים",
    body: "תזכורת והודעת תודה נשלחות ב-SMS. הודעה לפני אישורי הגעה נשלחת ב-WhatsApp. אין כאן ערוץ נוסף.",
    route: MESSAGES,
    selector: "[data-tour='message-sms-only']",
    advance: "continue",
  },
  {
    id: "go-activity",
    topic: "messages",
    title: "חזרה לתוצאות",
    learn: "איפה רואים שהסבב נרשם",
    body: "לחצו על דשבורד. בפעילות האחרונה מופיע הסבב שהודגם.",
    route: MESSAGES,
    stay: true,
    selector: "[data-tour='nav-dashboard']",
    advance: "click",
  },
  {
    id: "activity",
    topic: "messages",
    title: "הסבב ברשימת הפעילות",
    learn: "איך רואים סטטוס לדוגמה",
    body: "כאן מופיע שהסבב הודגם ושלא יצאה הודעה אמיתית. תשובות אורחים יתעדכנו גם בכרטיסים למעלה.",
    route: DASH,
    selector: "[data-tour='activity']",
    advance: "continue",
  },
  {
    id: "go-recorded",
    topic: "recorded",
    title: "כניסה לשיחות מוקלטות",
    learn: "איך מגיעים לסבב השיחות",
    body: "לחצו על ״שיחות מוקלטות״. אלה שיחות עם הודעה קולית, והאורח מאשר בהקשה על המקשים.",
    route: DASH,
    stay: true,
    selector: "[data-tour='nav-recorded-calls']",
    advance: "click",
  },
  {
    id: "call-name",
    topic: "recorded",
    title: "שם האירוע להקלטה",
    learn: "מה נאמר בשיחה",
    body: "כאן רושמים את שם האירוע שנשמע בשיחה. אפשר לעדכן אותו בדמו.",
    route: CALLS,
    selector: "[data-tour='call-event-name']",
    advance: "input",
  },
  {
    id: "call-ai",
    topic: "recorded",
    title: "קריינות",
    learn: "הודעה מוכנה",
    body: "לחצו על קריינות. זו הודעה קבועה, ורק שם האירוע משתנה.",
    route: CALLS,
    selector: "[data-tour='call-voice-ai']",
    advance: "click",
  },
  {
    id: "call-preview",
    topic: "recorded",
    title: "האזנה להודעה",
    learn: "תצוגה מקדימה בלי חיוג",
    body: "לחצו על הנגן. שומעים את מבנה השיחה בדמו, בלי שיחת טלפון.",
    route: CALLS,
    selector: "[data-tour='call-preview']",
    advance: "click",
  },
  {
    id: "call-approve",
    topic: "recorded",
    title: "אישור ההקלטה",
    learn: "לפני שקובעים סבב",
    body: "לחצו על אישור ההקלטה. בלי האישור הזה הסבב לא יוצא לשיחות.",
    route: CALLS,
    selector: "[data-tour='call-approve']",
    advance: "click",
  },
  {
    id: "call-self",
    topic: "recorded",
    title: "הקלטה אישית",
    learn: "אפשרות נוספת",
    body: "לחצו על הקלטה אישית. כך מעלים או מקליטים הודעה משלכם, במקום הקריינות.",
    route: CALLS,
    selector: "[data-tour='call-voice-self']",
    advance: "click",
  },
  {
    id: "call-time",
    topic: "recorded",
    title: "מועד סבב השיחות",
    learn: "תזמון בלי חיוג",
    body: "בחרו תאריך ושעה לסבב הראשון. השיחות היו יוצאות רק במועד הזה.",
    route: CALLS,
    selector: "[data-tour='call-round-time']",
    advance: "input",
  },
  {
    id: "call-save",
    topic: "recorded",
    title: "שמירת תזמון הסבב",
    learn: "איך הסבב נרשם",
    body: "לחצו שמירת תזמון. לא יוצאת שיחה. הסבב נשמר בדמו.",
    route: CALLS,
    selector: "[data-tour='call-schedule-save']",
    advance: "action",
    action: "ivr-schedule",
  },
  {
    id: "call-keypad",
    topic: "recorded",
    title: "הקשה של האורח",
    learn: "1 מגיע, 2 לא, 3 מתלבט",
    body: "בחרו אורח והקישו 1, 2 או 3. התשובה מתעדכנת בדמו בלי חיוג.",
    route: CALLS,
    selector: "[data-tour='call-keypad']",
    advance: "action",
    action: "ivr",
  },
  {
    id: "call-report",
    topic: "recorded",
    title: "דוח תוצאות השיחות",
    learn: "איפה רואים מה הקישו",
    body: "כאן רואים את תוצאת ההדמיה: מי הקיש ומה הסטטוס שהתעדכן.",
    route: CALLS,
    selector: "[data-tour='call-report']",
    advance: "continue",
  },
  {
    id: "go-human",
    topic: "human",
    title: "סבבי שיחות אנושיות",
    learn: "המסלול השני בחבילה",
    body: "לחצו על ״לו״ז אישורי הגעה״. אצל לקוח אמיתי מופיע רק סוג השיחות שנכלל בחבילה. בדמו מראים את שניהם.",
    route: CALLS,
    stay: true,
    selector: "[data-tour='nav-call-rounds']",
    advance: "click",
  },
  {
    id: "human-sim",
    topic: "human",
    title: "עדכון מהצוות",
    learn: "איך תשובה חוזרת לבעל האירוע",
    body: "לחצו על הדמיית עדכון מהצוות. זו לא שיחה אמיתית, והתשובה נרשמת אצלכם כמו אחרי שיחת צוות.",
    route: DASH,
    selector: "[data-tour='human-call-sim']",
    advance: "action",
    action: "human-call",
  },
  {
    id: "go-call-log",
    topic: "human",
    title: "איפה רואים את התיעוד",
    learn: "בלי מסך עובדים",
    body: "לחצו על רשימת המוזמנים. תיעוד השיחה נמצא בכרטיס האורח.",
    route: DASH,
    stay: true,
    selector: "[data-tour='nav-guests']",
    advance: "click",
  },
  {
    id: "call-log",
    topic: "human",
    title: "תיעוד השיחה אצל בעל האירוע",
    learn: "התשובה שהצוות עדכן",
    body: "לחצו על אייקון הטלפון. כאן רואים את תיעוד השיחות והתשובות, בלי להיכנס למסך צוות.",
    route: DASH,
    selector: "[data-tour='call-task']",
    advance: "click",
  },
  {
    id: "go-seating",
    topic: "seating",
    title: "כניסה לסידורי הושבה",
    learn: "איך מגיעים למפת האולם",
    body: "לחצו על ״סידורי הושבה״. משם רואים את האולם, השולחנות והאורחים שעדיין לא שובצו.",
    route: DASH,
    stay: true,
    selector: "[data-tour='nav-seating']",
    advance: "click",
  },
  {
    id: "seating-map",
    topic: "seating",
    title: "מפת האולם",
    learn: "איפה רואים את השולחנות",
    body: "זה אולם האירוע. כל שולחן מציג את המקומות ואת מי שכבר יושב.",
    route: SEATING,
    selector: "[data-tour='seating-map']",
    advance: "continue",
  },
  {
    id: "add-table",
    topic: "seating",
    title: "הוספת שולחן",
    learn: "איך פותחים שולחן חדש",
    body: "לחצו הוסף שולחן. בחלונית אפשר לבחור צורה וקיבולת.",
    route: SEATING,
    selector: "[data-tour='add-table']",
    advance: "click",
  },
  {
    id: "table-capacity",
    topic: "seating",
    title: "קיבולת השולחן",
    learn: "כמה אורחים נכנסים",
    body: "שנו את מספר האורחים בכל שולחן. זה מספר המקומות שייווצר.",
    route: SEATING,
    selector: "[data-tour='table-capacity']",
    advance: "input",
  },
  {
    id: "table-confirm",
    topic: "seating",
    title: "יצירת השולחן",
    learn: "איך השולחן נכנס למפה",
    body: "לחצו על כפתור ההוספה. השולחן החדש מופיע במפת האולם.",
    route: SEATING,
    selector: "[data-tour='table-add-confirm']",
    advance: "click",
  },
  {
    id: "seat-guest",
    topic: "seating",
    title: "שיבוץ אורח",
    learn: "איך מושיבים לשולחן",
    body: "לחצו הושב ליד אורח שעדיין לא יושב, ובחרו שולחן. הוא יופיע בשולחן.",
    route: SEATING,
    selector: "[data-tour='seating-guest']",
    advance: "action",
    action: "seat-guest",
  },
  {
    id: "seating-free",
    topic: "seating",
    title: "מקומות שנשארו",
    learn: "הקיבולת אחרי השיבוץ",
    body: "המספר הזה הוא האורחים שעדיין לא שובצו. אחרי שיבוץ הוא קטן.",
    route: SEATING,
    selector: "[data-tour='seating-capacity']",
    advance: "continue",
  },
  {
    id: "seating-move",
    topic: "seating",
    title: "העברה בין שולחנות",
    learn: "איך מעבירים אורח שיושב",
    body: "ליד אורח שכבר יושב יש בחירת שולחן. בחרו שולחן אחר כדי להעביר אותו.",
    route: SEATING,
    selector: "[data-tour='seating-move']",
    advance: "input",
  },
  {
    id: "seating-unseated",
    topic: "seating",
    title: "מי עוד לא שובץ",
    learn: "איך מסננים את הרשימה",
    body: "לחצו ״לא שובצו״. נשארת רשימת האורחים שעדיין בלי שולחן.",
    route: SEATING,
    selector: "[data-tour='seating-unseated']",
    advance: "click",
  },
  {
    id: "seating-back",
    topic: "checkin",
    title: "יציאה ממפת ההושבה",
    learn: "איך חוזרים לתפריט",
    body: "לחצו חזרה לדשבורד. משם נכנסים לכניסה לאירוע.",
    route: SEATING,
    selector: "[data-tour='seating-back']",
    advance: "click",
  },
  {
    id: "go-checkin",
    topic: "checkin",
    title: "כניסה לאירוע",
    learn: "איך פותחים את מסך הכניסה",
    body: "לחצו על ״כניסה לאירוע״. שם סורקים או מחפשים אורח ביום האירוע.",
    route: DASH,
    stay: true,
    selector: "[data-tour='nav-checkin']",
    advance: "click",
  },
  {
    id: "checkin-search",
    topic: "checkin",
    title: "חיפוש לפי שם או טלפון",
    learn: "כניסה בלי QR",
    body: "הקלידו שם או טלפון. כך מוצאים אורח גם בלי לסרוק.",
    route: CHECKIN,
    selector: "[data-tour='checkin-search']",
    advance: "input",
  },
  {
    id: "checkin-qr",
    topic: "checkin",
    title: "סריקת QR לדוגמה",
    learn: "סימון הגעה בפועל",
    body: "לחצו הדמיית סריקה, ואז בחרו כמה הגיעו. אין מצלמה ואין אירוע אמיתי.",
    route: CHECKIN,
    selector: "[data-tour='checkin-qr']",
    advance: "action",
    action: "check-in",
  },
  {
    id: "checkin-live",
    topic: "checkin",
    title: "המונה מתעדכן",
    learn: "כמה כבר נכנסו",
    body: "המספר הזה עלה לפי הכמות שסימנתם. אותו נתון חוזר גם לדשבורד.",
    route: CHECKIN,
    selector: "[data-tour='checkin-live']",
    advance: "continue",
  },
  {
    id: "go-summary",
    topic: "summary",
    title: "חזרה לתמונת המצב",
    learn: "איפה רואים את כל מה שעשיתם",
    body: "לחצו על דשבורד. הכרטיסים כוללים את התשובות, ההושבה והכניסה מהסיור.",
    route: CHECKIN,
    stay: true,
    selector: "[data-tour='nav-dashboard']",
    advance: "click",
  },
  {
    id: "reports",
    topic: "summary",
    title: "הנתונים אחרי הסיור",
    learn: "הדוח החי של האירוע",
    body: "מגיעים, ממתינים ופעילות אחרונה כבר כוללים את הפעולות שביצעתם בדמו.",
    route: DASH,
    selector: "#rsvp-stats",
    advance: "continue",
  },
];

export function tourStepCount() {
  return DEMO_TOUR_STEPS.length;
}

export function tourTopicIndex(topic: string) {
  return DEMO_TOUR_TOPICS.findIndex((item) => item.id === topic);
}
