import type { WeddingSectionId, WeddingTemplate } from "@/types/weddingWebsite";
import { WW_IMAGES, gallerySet } from "./media";

export const WEDDING_SECTIONS: {
  id: WeddingSectionId;
  label: string;
  navLabel: string;
}[] = [
  { id: "hero", label: "Hero", navLabel: "בית" },
  { id: "countdown", label: "Countdown", navLabel: "ספירה" },
  { id: "invitation", label: "Invitation", navLabel: "הזמנה" },
  { id: "our-story", label: "Our Story", navLabel: "סיפור" },
  { id: "how-we-met", label: "How We Met", navLabel: "איך נפגשנו" },
  { id: "proposal", label: "Proposal", navLabel: "הצעה" },
  { id: "gallery", label: "Gallery", navLabel: "גלריה" },
  { id: "video", label: "Video", navLabel: "וידאו" },
  { id: "event-details", label: "Details", navLabel: "פרטים" },
  { id: "schedule", label: "Schedule", navLabel: "לוח זמנים" },
  { id: "location", label: "Location", navLabel: "מיקום" },
  { id: "dress-code", label: "Dress Code", navLabel: "לבוש" },
  { id: "accommodations", label: "Hotels", navLabel: "לינה" },
  { id: "transportation", label: "Transport", navLabel: "הגעה" },
  { id: "faq", label: "FAQ", navLabel: "שאלות" },
  { id: "rsvp", label: "RSVP", navLabel: "אישור הגעה" },
  { id: "gifts", label: "Gifts", navLabel: "מתנות" },
  { id: "guestbook", label: "Guestbook", navLabel: "ברכות" },
  { id: "guest-upload", label: "Uploads", navLabel: "זיכרונות" },
  { id: "playlist", label: "Playlist", navLabel: "מוזיקה" },
  { id: "footer", label: "Footer", navLabel: "סיום" },
];

/** Primary sticky-nav items — rest go into "עוד" menu (no horizontal scroll) */
export const WEDDING_NAV_PRIMARY: WeddingSectionId[] = [
  "our-story",
  "gallery",
  "schedule",
  "location",
  "faq",
  "rsvp",
];

export const WEDDING_TEMPLATES: WeddingTemplate[] = [
  {
    id: "eternal-gold",
    name: "Eternal Gold",
    tagline: "יוקרה קלאסית בזהב ושמפניה",
    description:
      "תבנית אלגנטית עם זהב עדין, טיפוגרפיה serif ואנימציות רכות — מושלמת לחתונה formal.",
    previewImage: WW_IMAGES.ceremony,
    heroImage: WW_IMAGES.outdoorCouple,
    galleryImages: gallerySet(
      "venueArch",
      "coupleClose",
      "florals",
      "aisleWalk",
      "ringsHands",
      "celebration"
    ),
    mood: "classic",
    theme: {
      bg: "#FAF7F2",
      bgAlt: "#F3EBE0",
      surface: "#FFFFFF",
      text: "#2A2118",
      textMuted: "#8A7560",
      accent: "#C9A962",
      accentSoft: "#E8D5A8",
      border: "rgba(201, 169, 98, 0.35)",
      heroOverlay:
        "linear-gradient(180deg, rgba(20,14,8,0.25) 0%, rgba(20,14,8,0.72) 100%)",
      fontDisplay: "'Cormorant Garamond', serif",
      fontBody: "'Heebo', sans-serif",
      radius: "28px",
      shadow: "0 24px 80px rgba(92, 65, 35, 0.14)",
      grain: true,
    },
  },
  {
    id: "midnight-velvet",
    name: "Midnight Velvet",
    tagline: "לילה שחור עם נגיעות זהב",
    description:
      "דרמה מודרנית — רקע כהה, נגיעות זהב, parallax ואפקטים קולנועיים.",
    previewImage: WW_IMAGES.tableSetting,
    heroImage: WW_IMAGES.nightGlow,
    galleryImages: gallerySet(
      "elegantHall",
      "kiss",
      "ringsHands",
      "celebration",
      "outdoorCouple",
      "softPortrait"
    ),
    mood: "dramatic",
    theme: {
      bg: "#0D0B10",
      bgAlt: "#16131C",
      surface: "#1E1A26",
      text: "#F5F0E8",
      textMuted: "#A89BB0",
      accent: "#D4AF37",
      accentSoft: "#3D3520",
      border: "rgba(212, 175, 55, 0.25)",
      heroOverlay:
        "linear-gradient(180deg, rgba(0,0,0,0.2) 0%, rgba(0,0,0,0.85) 100%)",
      fontDisplay: "'Playfair Display', serif",
      fontBody: "'Heebo', sans-serif",
      radius: "20px",
      shadow: "0 30px 90px rgba(0, 0, 0, 0.55)",
      grain: true,
    },
  },
  {
    id: "garden-bloom",
    name: "Garden Bloom",
    tagline: "פרחים, ירוק רך ורומנטיקה",
    description: "אווירת גן — עלים, פרחים, gradients רכים ואנימציות float.",
    previewImage: WW_IMAGES.florals,
    heroImage: WW_IMAGES.kiss,
    galleryImages: gallerySet(
      "florals",
      "bouquet",
      "outdoorCouple",
      "venueArch",
      "softPortrait",
      "aisleWalk"
    ),
    mood: "floral",
    theme: {
      bg: "#F4FAF4",
      bgAlt: "#E8F3E8",
      surface: "#FFFFFF",
      text: "#1F3324",
      textMuted: "#5C7A62",
      accent: "#6B9E78",
      accentSoft: "#C8E6C9",
      border: "rgba(107, 158, 120, 0.3)",
      heroOverlay:
        "linear-gradient(180deg, rgba(30,50,35,0.22) 0%, rgba(30,50,35,0.68) 100%)",
      fontDisplay: "'Libre Baskerville', serif",
      fontBody: "'Heebo', sans-serif",
      radius: "32px",
      shadow: "0 20px 60px rgba(60, 100, 70, 0.12)",
      grain: false,
    },
  },
  {
    id: "coastal-breeze",
    name: "Coastal Breeze",
    tagline: "ים, תכלת ואור ים תיכוני",
    description: "חתונה על חוף — גווני כחול, לבן, גלים ותחושת קיץ.",
    previewImage: WW_IMAGES.beachCouple,
    heroImage: WW_IMAGES.beachCouple,
    galleryImages: gallerySet(
      "beachCouple",
      "coupleClose",
      "outdoorCouple",
      "ceremony",
      "florals",
      "softPortrait"
    ),
    mood: "coastal",
    theme: {
      bg: "#F0F8FF",
      bgAlt: "#E3F2FD",
      surface: "#FFFFFF",
      text: "#0D2840",
      textMuted: "#5A7A94",
      accent: "#3D8BBA",
      accentSoft: "#B3E0F2",
      border: "rgba(61, 139, 186, 0.28)",
      heroOverlay:
        "linear-gradient(180deg, rgba(10,40,60,0.18) 0%, rgba(10,40,60,0.62) 100%)",
      fontDisplay: "'Montserrat', sans-serif",
      fontBody: "'Heebo', sans-serif",
      radius: "24px",
      shadow: "0 22px 70px rgba(30, 80, 120, 0.12)",
      grain: false,
    },
  },
  {
    id: "desert-rose",
    name: "Desert Rose",
    tagline: "טרakota, ורוד עמוק וחול",
    description: "חתונה חמה — גוונים חמים, textures ואנימציות shimmer.",
    previewImage: WW_IMAGES.aisleWalk,
    heroImage: WW_IMAGES.coupleClose,
    galleryImages: gallerySet(
      "coupleClose",
      "aisleWalk",
      "kiss",
      "venueArch",
      "bouquet",
      "ringsHands"
    ),
    mood: "warm",
    theme: {
      bg: "#FBF5F0",
      bgAlt: "#F5E8DE",
      surface: "#FFFFFF",
      text: "#3D2518",
      textMuted: "#9A7060",
      accent: "#C4705A",
      accentSoft: "#E8C4B8",
      border: "rgba(196, 112, 90, 0.3)",
      heroOverlay:
        "linear-gradient(180deg, rgba(60,30,20,0.28) 0%, rgba(60,30,20,0.7) 100%)",
      fontDisplay: "'Cormorant Garamond', serif",
      fontBody: "'Heebo', sans-serif",
      radius: "26px",
      shadow: "0 24px 75px rgba(120, 60, 40, 0.14)",
      grain: true,
    },
  },
  {
    id: "minimal-noir",
    name: "Minimal Noir",
    tagline: "שחור, לבן, typography בלבד",
    description: "מינימלי יוקרתי — whitespace, קווים דקים, motion עדין.",
    previewImage: WW_IMAGES.elegantHall,
    heroImage: WW_IMAGES.softPortrait,
    galleryImages: gallerySet(
      "softPortrait",
      "elegantHall",
      "ringsHands",
      "nightGlow",
      "ceremony",
      "kiss"
    ),
    mood: "minimal",
    theme: {
      bg: "#FAFAFA",
      bgAlt: "#F0F0F0",
      surface: "#FFFFFF",
      text: "#111111",
      textMuted: "#666666",
      accent: "#111111",
      accentSoft: "#E5E5E5",
      border: "rgba(0, 0, 0, 0.12)",
      heroOverlay:
        "linear-gradient(180deg, rgba(0,0,0,0.12) 0%, rgba(0,0,0,0.65) 100%)",
      fontDisplay: "'Montserrat', sans-serif",
      fontBody: "'Heebo', sans-serif",
      radius: "8px",
      shadow: "0 16px 48px rgba(0, 0, 0, 0.08)",
      grain: false,
    },
  },
  {
    id: "royal-ivory",
    name: "Royal Ivory",
    tagline: "קרם מלכותי עם עיטור עדין",
    description: "palace wedding — ivory, מסגרות עדינות, fade-in אלגנטי.",
    previewImage: WW_IMAGES.kiss,
    heroImage: WW_IMAGES.venueArch,
    galleryImages: gallerySet(
      "venueArch",
      "outdoorCouple",
      "ceremony",
      "kiss",
      "ringsHands",
      "aisleWalk"
    ),
    mood: "royal",
    theme: {
      bg: "#FDFBF7",
      bgAlt: "#F7F2EA",
      surface: "#FFFFFF",
      text: "#2C2419",
      textMuted: "#8C7B68",
      accent: "#B8956B",
      accentSoft: "#E8DDD0",
      border: "rgba(184, 149, 107, 0.32)",
      heroOverlay:
        "linear-gradient(180deg, rgba(40,30,20,0.24) 0%, rgba(40,30,20,0.66) 100%)",
      fontDisplay: "'Playfair Display', serif",
      fontBody: "'Heebo', sans-serif",
      radius: "30px",
      shadow: "0 26px 85px rgba(100, 75, 50, 0.12)",
      grain: true,
    },
  },
  {
    id: "sunset-blush",
    name: "Sunset Blush",
    tagline: "ורוד, כתום ושקיעה",
    description: "שקיעה רומנטית — gradients רכים, קו עדין, אווירה חמה.",
    previewImage: WW_IMAGES.florals,
    heroImage: WW_IMAGES.aisleWalk,
    galleryImages: gallerySet(
      "aisleWalk",
      "florals",
      "coupleClose",
      "ceremony",
      "softPortrait",
      "bouquet"
    ),
    mood: "romantic",
    theme: {
      bg: "#FFF5F7",
      bgAlt: "#FFE8EE",
      surface: "#FFFFFF",
      text: "#3D1F28",
      textMuted: "#9A6070",
      accent: "#E8788A",
      accentSoft: "#FFD4DC",
      border: "rgba(232, 120, 138, 0.28)",
      heroOverlay:
        "linear-gradient(180deg, rgba(80,20,40,0.22) 0%, rgba(80,20,40,0.66) 100%)",
      fontDisplay: "'Cormorant Garamond', serif",
      fontBody: "'Heebo', sans-serif",
      radius: "28px",
      shadow: "0 22px 72px rgba(180, 80, 100, 0.14)",
      grain: false,
    },
  },
  {
    id: "forest-enchanted",
    name: "Forest Enchanted",
    tagline: "יער קסום, ירוק עמוק",
    description: "חתונה בטבע — עלים, אור רך, אווירה enchanted.",
    previewImage: WW_IMAGES.outdoorCouple,
    heroImage: WW_IMAGES.outdoorCouple,
    galleryImages: gallerySet(
      "outdoorCouple",
      "florals",
      "kiss",
      "venueArch",
      "bouquet",
      "softPortrait"
    ),
    mood: "nature",
    theme: {
      bg: "#0F1810",
      bgAlt: "#162118",
      surface: "#1C2A1E",
      text: "#E8F0E4",
      textMuted: "#8AA892",
      accent: "#7CB87A",
      accentSoft: "#2A4030",
      border: "rgba(124, 184, 122, 0.28)",
      heroOverlay:
        "linear-gradient(180deg, rgba(5,15,8,0.3) 0%, rgba(5,15,8,0.8) 100%)",
      fontDisplay: "'Libre Baskerville', serif",
      fontBody: "'Heebo', sans-serif",
      radius: "24px",
      shadow: "0 28px 90px rgba(0, 20, 10, 0.45)",
      grain: true,
    },
  },
  {
    id: "modern-glass",
    name: "Modern Glass",
    tagline: "Glassmorphism עכשווי",
    description: "blur, glass panels, accents קרים — Gen-Z luxury.",
    previewImage: WW_IMAGES.nightGlow,
    heroImage: WW_IMAGES.elegantHall,
    galleryImages: gallerySet(
      "elegantHall",
      "nightGlow",
      "softPortrait",
      "celebration",
      "ringsHands",
      "ceremony"
    ),
    mood: "modern",
    theme: {
      bg: "#0A0E17",
      bgAlt: "#121828",
      surface: "rgba(255,255,255,0.06)",
      text: "#F0F4FF",
      textMuted: "#8892A8",
      accent: "#7C9CFF",
      accentSoft: "rgba(124, 156, 255, 0.18)",
      border: "rgba(255, 255, 255, 0.12)",
      heroOverlay:
        "linear-gradient(180deg, rgba(5,10,20,0.28) 0%, rgba(5,10,20,0.86) 100%)",
      fontDisplay: "'Montserrat', sans-serif",
      fontBody: "'Heebo', sans-serif",
      radius: "20px",
      shadow: "0 24px 80px rgba(0, 0, 0, 0.4)",
      grain: false,
    },
  },
];

export function getWeddingTemplate(id: string) {
  return WEDDING_TEMPLATES.find((t) => t.id === id) ?? null;
}

export function getWeddingTemplateIds() {
  return WEDDING_TEMPLATES.map((t) => t.id);
}
