/**
 * Design contracts for the 10 wedding templates.
 * Each must remain visually and structurally distinct.
 */
export const TEMPLATE_CONCEPTS = {
  "eternal-gold": {
    name: "Eternal Gold",
    visualConcept: "Luxury classic champagne formal",
    hero: "Full-bleed photo ken-burns, centered serif names, gold diamond divider",
    animationLanguage: "Slow fade-up + gold scroll progress line",
    signatureElement: "GoldScrollLine",
    sectionOrder: [
      "hero",
      "countdown",
      "invitation",
      "our-story",
      "gallery",
      "schedule",
      "location",
      "transportation",
      "rsvp",
      "faq",
      "gifts",
      "footer",
    ],
    differentiator: "Formal rhythm, gold rules, classic centered composition",
  },
  "midnight-velvet": {
    name: "Midnight Velvet",
    visualConcept: "Cinematic black-tie night",
    hero: "Widescreen video frame with starfield + gold title glow",
    animationLanguage: "Star twinkle, soft glow reveals, vertical drama",
    signatureElement: "Starfield",
    sectionOrder: [
      "hero",
      "event-details",
      "our-story",
      "schedule",
      "gallery",
      "location",
      "transportation",
      "rsvp",
      "gifts",
      "faq",
      "footer",
    ],
    differentiator: "Dark cinema frame, stars, gold-on-black RSVP",
  },
  "garden-bloom": {
    name: "Garden Bloom",
    visualConcept: "Romantic botanical garden",
    hero: "Soft portrait with floating petals and organic curves",
    animationLanguage: "Floating petals, bloom fades, soft float-in cards",
    signatureElement: "FloatingPetals",
    sectionOrder: [
      "hero",
      "our-story",
      "how-we-met",
      "gallery",
      "schedule",
      "location",
      "transportation",
      "dress-code",
      "rsvp",
      "faq",
      "gifts",
      "footer",
    ],
    differentiator: "Botanical motion, green palette, story-first flow",
  },
  "coastal-breeze": {
    name: "Coastal Breeze",
    visualConcept: "Mediterranean summer light",
    hero: "Beach video/photo horizon with airy Montserrat type",
    animationLanguage: "Wave edges, shuttle ride, breezy fades",
    signatureElement: "ShuttleRide + waves",
    sectionOrder: [
      "hero",
      "countdown",
      "event-details",
      "location",
      "transportation",
      "schedule",
      "gallery",
      "rsvp",
      "faq",
      "gifts",
      "footer",
    ],
    differentiator: "Sea palette, wave separators, travel-first flow",
  },
  "desert-rose": {
    name: "Desert Rose",
    visualConcept: "Warm terracotta watercolor romance",
    hero: "Diagonal clipped portrait with watercolor reveal",
    animationLanguage: "Watercolor circle reveals, diagonal wipes",
    signatureElement: "WatercolorReveal",
    sectionOrder: [
      "hero",
      "invitation",
      "our-story",
      "gallery",
      "schedule",
      "location",
      "transportation",
      "rsvp",
      "gifts",
      "faq",
      "footer",
    ],
    differentiator: "Diagonal geometry + watercolor reveals",
  },
  "minimal-noir": {
    name: "Minimal Noir",
    visualConcept: "Editorial black & white typography",
    hero: "Split oversized names, no photo dominance",
    animationLanguage: "Precise slide-ins, hairline progress, almost still",
    signatureElement: "Progress hairline",
    sectionOrder: [
      "hero",
      "event-details",
      "schedule",
      "location",
      "rsvp",
      "gallery",
      "faq",
      "footer",
    ],
    differentiator: "Typography-first, sparse sections, ink buttons",
  },
  "royal-ivory": {
    name: "Royal Ivory",
    visualConcept: "Palace ivory monogram ceremony",
    hero: "Centered crest/monogram letter frame",
    animationLanguage: "Elegant scale fades, envelope RSVP open",
    signatureElement: "EnvelopeRsvp",
    sectionOrder: [
      "hero",
      "invitation",
      "schedule",
      "our-story",
      "gallery",
      "location",
      "transportation",
      "rsvp",
      "faq",
      "gifts",
      "footer",
    ],
    differentiator: "Crest hero + envelope RSVP ceremony",
  },
  "sunset-blush": {
    name: "Sunset Blush",
    visualConcept: "Soft pastel dusk romance",
    hero: "Gradient dusk sky with soft couple names",
    animationLanguage: "Polaroid cascade, blush fades",
    signatureElement: "PolaroidGallery",
    sectionOrder: [
      "hero",
      "countdown",
      "our-story",
      "gallery",
      "schedule",
      "location",
      "transportation",
      "rsvp",
      "gifts",
      "faq",
      "footer",
    ],
    differentiator: "Polaroid gallery language + blush gradients",
  },
  "forest-enchanted": {
    name: "Forest Enchanted",
    visualConcept: "Deep woodland night path",
    hero: "Dark forest full-bleed with moss accents",
    animationLanguage: "Path-draw timeline, soft firefly-like dots",
    signatureElement: "PathDrawTimeline",
    sectionOrder: [
      "hero",
      "our-story",
      "schedule",
      "gallery",
      "location",
      "transportation",
      "rsvp",
      "faq",
      "gifts",
      "footer",
    ],
    differentiator: "Drawn forest path schedule, dark nature mood",
  },
  "modern-glass": {
    name: "Modern Glass",
    visualConcept: "Bold editorial glass fashion",
    hero: "Asymmetric bento grid with glass panels + video cell",
    animationLanguage: "Staggered editorial reveals, glass blur",
    signatureElement: "Bento / glass stagger",
    sectionOrder: [
      "hero",
      "event-details",
      "gallery",
      "schedule",
      "location",
      "transportation",
      "rsvp",
      "faq",
      "footer",
    ],
    differentiator: "Bento hero + glass cards + fashion type",
  },
} as const;
